<?php
/**
 * Favicon.
 *
 * Falls back to the theme-bundled `favicon.png` (theme root, not `src/`, so it
 * ships as-is with no webpack copy step) only when no Site Icon has been set via
 * Customizer > Site Identity. Filtering `get_site_icon_url` — rather than printing
 * a hand-rolled <link> on wp_head — lets core's own `wp_site_icon()` output handle
 * every icon size, apple-touch-icon, and the admin/RSS favicons for us.
 *
 * @package resume
 */

add_filter(
	'get_site_icon_url',
	function ( $url ) {
		return $url ? $url : get_stylesheet_directory_uri() . '/favicon.png';
	}
);

// Register the theme's custom blocks from the build/ directory, using the blocks-manifest.php
// generated by the build step. This is the documented way to register blocks from a theme.
add_action( 'init', function () {
    wp_register_block_types_from_metadata_collection( get_stylesheet_directory() . '/build', get_stylesheet_directory() . '/build/blocks-manifest.php' );
} );


// Custom Dark Mode Toggle Block.
if ( function_exists( 'tabordarkmodetoggleblock_init' ) ) {
    add_action('wp_enqueue_scripts', function () {
        // Frontend
        wp_enqueue_style(
            'resume-dark-mode',
            get_template_directory_uri() . '/build/css/dark-mode.css',
            array(),
            filemtime( get_template_directory() . '/build/css/dark-mode.css' )
        );
    } );

	add_action( 'after_setup_theme', function () {
		add_editor_style( 'build/css/dark-mode.css' );
	} );
}


/**
 * Custom block styles (register_block_style()), for core and third-party blocks.
 *
 * register_block_style() (rather than a hand-rolled `wp.blocks.registerBlockStyle()` +
 * manual style enqueue) is the documented way to add these: WordPress registers the style
 * for the editor's Styles panel and prints `inline_style` on both front end and editor by
 * itself.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/
 * @package resume
 */

add_action(
	'init',
	function () {
		// "Primary bullet" / "Secondary bullet" — color individual core/list-item markers
		// with the theme's Primary/Secondary palette, picked per item from the Styles panel.
		register_block_style(
			'core/list-item',
			array(
				'name'         => 'primary-bullet',
				'label'        => __( 'Primary bullet', 'resume' ),
				// The Style Engine has no "marker" element support, so the color needs raw CSS.
				'inline_style' => 'li.is-style-primary-bullet::marker{color:var(--wp--preset--color--primary)}',
			)
		);

		register_block_style(
			'core/list-item',
			array(
				'name'         => 'secondary-bullet',
				'label'        => __( 'Secondary bullet', 'resume' ),
				'inline_style' => 'li.is-style-secondary-bullet::marker{color:var(--wp--preset--color--secondary)}',
			)
		);
	}
);